### ISSUE TITLE
Remove action keyword when configuring actions

### ISSUE THREAD

**Issue by MarioBlazek** [netgen/NetgenInformationCollectionBundle#1]
Currently configuration looks like this:
```yml
ng_feedback_form:
    - action: email
    - action: database
```
it would be better to have something like this:
```yml
ng_feedback_form:
    actions:
        - email
        - database
```
