### ISSUE TITLE
Different twig templates for different custom email actions

### ISSUE THREAD

**Issue by lucagentile** [netgen/NetgenInformationCollectionBundle#22]
Hi,

it would be great to have custom email actions use different templates from the default one.

Something like:
```
netgen_information_collection:
    system:
        default:
            action_config:
                email:
                    templates:
                        default: "Bundle:email.html.twig"
                        actions:
                               email:
                                     content_types:
                                            contact_us "email:contact_us.html.twig"
                                            work_with_us: "email:work_with_us.html.twig"
                               email_to_sender:
                                     content_types:
                                            contact_us: "email:contact_us2.html.twig"
                                            work_with_us: "email:work_with_us2.html.twig"
                    default_variables:
                        sender: ""
                        recipient: ""
            actions:
                default:
                    - email
                    - database
                    - email_to_sender
```
