### ISSUE TITLE
Enable seamless adding of collected info classes & objects

### ISSUE THREAD

**Issue by emodric** [netgen/NetgenInformationCollectionBundle#5]
Currently, every class that collects info needs to have a config counterpart, which seriously hinders editors ability to add forms on the fly.

It would be great to provide a (configurable) default actions config which would be used for all classes that do not have specific config.

**Comment by MarioBlazek** [comment]
New configuration example. 

```yml
netgen_information_collection:
    system:
        default:
            actions:
                default:
                    - email
                    - database
                content_type:
                    ng_feedback_form:
                        - custom_action
                    si_order_spare_part:
                        - custom_action_2
                        - database
```
